# Generated by Django 5.0.3 on 2024-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashisland',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trashisland',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
