# Generated by Django 5.0.3 on 2024-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0003_alter_sensordata_options_alter_trashcan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
