# Generated by Django 5.0.3 on 2024-04-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0004_sensordata_humidity_sensordata_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='humidity',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temperature',
        ),
    ]
