# Generated by Django 5.0.3 on 2024-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0005_rename_humidity_sensordata_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='fill_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
