# Generated by Django 5.0.3 on 2024-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0006_sensordata_fill_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trashcan',
            name='status',
        ),
        migrations.AddField(
            model_name='trashcan',
            name='fill_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
