# Generated by Django 5.0.3 on 2024-04-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0007_remove_sensordata_status_remove_trashcan_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='fill_amount',
            new_name='fill_percentage',
        ),
        migrations.RenameField(
            model_name='trashcan',
            old_name='fill_amount',
            new_name='fill_percentage',
        ),
    ]
