# Generated by Django 5.0.4 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0008_rename_fill_amount_sensordata_fill_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='MAC_adress',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='time_interval',
            field=models.TimeField(null=True),
        ),
    ]
