# Generated by Django 5.0.4 on 2024-05-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0009_trashcan_mac_adress_trashcan_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='time_interval',
            field=models.IntegerField(null=True),
        ),
    ]
