# Generated by Django 5.0.4 on 2024-05-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0010_alter_trashcan_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='MAC_adress',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
