# Generated by Django 5.0.3 on 2024-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_route_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.TextField(),
        ),
    ]
