# Generated by Django 5.0.3 on 2024-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_route_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_name',
        ),
    ]
