# Generated by Django 5.0.3 on 2024-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_route_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='adresses',
            field=models.TextField(),
        ),
    ]
