# Generated by Django 5.0.3 on 2024-04-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_route_adresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='Rute 1', max_length=255),
        ),
    ]
