# Generated by Django 5.0.4 on 2024-05-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0012_alter_trashcan_capacity'),
        ('operations', '0007_alter_route_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='adresses',
        ),
        migrations.AddField(
            model_name='route',
            name='trashcan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datacollector.trashcan'),
        ),
    ]
