# Generated by Django 5.0.4 on 2024-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_route_adresses_route_trashcan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='trashcan',
        ),
        migrations.AddField(
            model_name='route',
            name='adresses',
            field=models.TextField(default=''),
        ),
    ]
