<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-06 10:22
=======
# Generated by Django 4.2.4 on 2024-05-06 09:12
>>>>>>> 511c6e401560bb29bda9830e79017a489f886c3d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
